### ISSUE TITLE
Incorrect minimum Python version

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/geemap-feedstock#174]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This conda-forge package indicates `python >=3.7` as the Python dependency.  However, as seen in the [Github repo](https://github.com/gee-community/geemap/blob/v0.20.5/setup.py), the upstream project has required `python >=3.8` since geemap v0.20.5.

NOTE: I have not checked the other dependencies of this project for correctness.  I encountered the Python version problem, so only verified that.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by giswqs** [comment]
Fixed in #175

**Comment by DManowitz** [comment]
Just looked at PR #175, and it doesn't actually fix the required Python version for this package - it only updated the **host** requirement, not the **run** requirement!
